Feature/curriculum topic
revabam/pebbles-curriculum pull request #13
Opened 2018-09-24 15:46 UTC by humphreyminottjr

2018-09-24 18:27 UTC, danielsidhu commented on src/main/java/com/revature/models/CurriculumTopic.java
>  	public CurriculumTopic(Integer curriculum_id, Integer topic_id, Integer number_of_weeks) {
Why are curriculum id, topic id and number of weeks still snake cased? are they snake cased somewhere else within the application?

2018-09-24 18:28 UTC, danielsidhu commented on src/main/java/com/revature/models/CurriculumTopic.java
> +		this.numberOfWeeks = number_of_weeks;
this keyword variables still snake cased

2018-09-24 18:29 UTC, danielsidhu commented on src/main/java/com/revature/models/CurriculumTopic.java
> +		this.numberOfWeeks = number_of_weeks;
getter n' setter for number of weeks still snake cased

2018-09-24 18:33 UTC, danielsidhu commented on src/main/java/com/revature/models/CurriculumTopic.java
> +
be sure to have only one empty line space between methods. good eye on the snake casing

2018-09-24 19:51 UTC, danielsidhu submitted a review, later dismissed

2018-09-25 14:22 UTC, ChineduOzodi requested changes
Please delete the target folder (mvn clean) and add the folder to the .gitignore

2018-09-26 20:47 UTC, ChineduOzodi requested changes
Bunch of commented out code that needs to be fixed or deleted. Also make sure to delete the target folder (mvn clean) and add target/ to the .gitignore

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/java/com/revature/controllers/CurriculumController.java
> +//	}
Delete commented out code. If you need it later on you can store it in a git snippet

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/java/com/revature/controllers/CurriculumController.java
>  		return new ResponseEntity<>(topic, HttpStatus.CREATED);
Delete commented out code

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/java/com/revature/controllers/CurriculumController.java
> +//	}
Delete commented out code

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/java/com/revature/models/CurriculumWeek.java
> +
Delete commented out code

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/java/com/revature/services/CurriculumService.java
Remove commented out code.

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/java/com/revature/services/CurriculumService.java
> +//	}
Remove commented out code

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/resources/data.sql
> +-- values(7, 2, 3, 4);
Remove commented out code

2018-09-26 20:47 UTC, ChineduOzodi commented on src/main/resources/schema.sql
> +-- FOREIGN KEY (topic_id) references topic(id));
remove commented out code.

2018-09-26 20:47 UTC, ChineduOzodi commented on src/test/java/com/revature/tests/curriculumTest/CurriculumTest.java
> +//		assertEquals(testSubtopic.getParent_topicid(), sub.getParent_topic_id());
Remove commented out code.

2018-09-26 20:47 UTC, ChineduOzodi commented on target/classes/META-INF/MANIFEST.MF
> +Created-By: Maven Integration for Eclipse
delete the target folder (mvn clean), add target/ to .gitignore

2018-09-28 23:48 UTC, danielsidhu commented on src/main/resources/schema.sql
>  -- DROP CONSTRAINT FKN59K91C6XDUUKIJFEJ2IVN5AD;
is this required at all? otherwise please delete.

2018-09-28 23:51 UTC, danielsidhu commented on src/main/java/com/revature/controllers/CurriculumController.java
> +		System.out.println("GET METHODHIT");
delete after done using.

2018-09-28 23:53 UTC, danielsidhu commented on src/main/java/com/revature/controllers/CurriculumController.java
> +//	}
commented code, please delete if not required for the application

2018-09-28 23:54 UTC, danielsidhu commented on src/main/java/com/revature/models/Curriculum.java
>  	@NotNull
not sure about the spacing here but be sure to have a maximum of only one line of space between the fields or methods of the pojo

2018-09-28 23:58 UTC, danielsidhu commented on src/main/java/com/revature/models/CurriculumDay.java
> +	 */
what is this used for? otherwise please delete.

2018-09-28 23:59 UTC, danielsidhu commented on src/main/java/com/revature/models/CurriculumDay.java
> +
only one line of space between methods

2018-09-29 00:02 UTC, danielsidhu commented on src/main/java/com/revature/models/CurriculumWeek.java
> +	public CurriculumWeek() {
one line of space between line 43 and 46

2018-09-29 00:02 UTC, danielsidhu commented on src/main/java/com/revature/models/Subtopic.java
> +//	private String name;
commented out code

2018-09-29 00:03 UTC, danielsidhu reviewed
So I went through about half way on this and probably realized this still needs work on so I will leave this until I get notice to merge.

2018-10-01 14:27 UTC, ChineduOzodi approved these changes

2018-10-01 14:28 UTC, merged